---
- name: add inbound rule for port 80 on ec2 security groups
  hosts: ec2_instances
  gather_facts: true
  tasks:
    - name: Get security group details
      amazon.aws.ec2_group_info:
       region: us-east-2
      register: security_groups
      
    - name: Extract security group IDs
      set_fact:
        sg_ids: "{{ security_groups.security_groups | map(attribute='group_id') | list }}"

    - name: Add inbound rule for HTTP (port 80)
      amazon.aws.ec2_security_group:
        region: us-east-2
        group_id: "{{ item }}"
        rules:
          - proto: tcp
            ports: "80"
            cidr_ip: "0.0.0.0/0"
        state: present
      loop: "{{ sg_ids }}"
      delegate_to: localhost