---
- hosts: all
  become: true

  tasks:
    - name: Update package lists
      ansible.builtin.apt:
        update_cache: yes

    - name: Ensure OpenSSH and OpenSSL are installed
      ansible.builtin.apt:
        name: 
          - openssh-server
          - openssl
        state: latest  

    - name: Check if Docker is installed
      ansible.builtin.command: docker --version
      register: docker_installed
      ignore_errors: yes
      changed_when: false

    - name: Debug Docker version output
      ansible.builtin.debug:
        var: docker_installed.stdout

    - name: Install prerequisites for Docker
      ansible.builtin.apt:
        name:
          - apt-transport-https
          - ca-certificates
          - curl
          - software-properties-common
        state: present
      when: docker_installed.rc != 0

    - name: Add Docker’s official GPG key
      ansible.builtin.shell: |
        curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo gpg --dearmor -o /usr/share/keyrings/docker-archive-keyring.gpg
      args:
        executable: /bin/bash
      when: docker_installed.rc != 0

    - name: Add Docker repository
      ansible.builtin.shell: |
        echo "deb [arch=amd64 signed-by=/usr/share/keyrings/docker-archive-keyring.gpg] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable" | sudo tee /etc/apt/sources.list.d/docker.list > /dev/null
      args:
        executable: /bin/bash
      when: docker_installed.rc != 0

    - name: Update package lists again
      ansible.builtin.apt:
        update_cache: yes
      when: docker_installed.rc != 0

    - name: Install Docker
      ansible.builtin.apt:
        name: docker-ce
        state: present
      when: docker_installed.rc != 0

    - name: Start and enable Docker service
      ansible.builtin.systemd:
        name: docker
        state: started
        enabled: yes
      when: docker_installed.rc != 0

    - name: Verify Docker installation
      ansible.builtin.command: docker --version
      register: docker_version_output
      changed_when: false

    - name: Show Docker version
      ansible.builtin.debug:
        msg: "Docker installed successfully: {{ docker_version_output.stdout }}"
